name: Build nightly

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  generator:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build standard
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get tools
        run: |
          wget "https://github.com/ihaveamac/ctr_toolkit/releases/download/make_cia6.4builds/make_cia6.4builds.zip"
          unzip make_cia6.4builds.zip
          sudo cp linux/make_cia /usr/local/bin/make_cia && sudo chmod +x /usr/local/bin/make_cia
      - name: Make YANBF
        run: |
          make dist
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: dist
          name: YANBF

  windows:
    runs-on: windows-2019
    name: Build Windows
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: generator
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: YANBF
          path: YANBF
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pyinstaller
        run: |
          py -m pip install -r YANBF/generator/requirements.txt
      - name: Create package
        run: |
          curl -LJO "https://github.com/Epicpkmn11/bannertool/releases/download/1.2.1/bannertool.zip"
          unzip bannertool.zip
          move windows-x86_64\bannertool.exe YANBF/generator/bannertool.exe
          curl -LJO "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-win_x86_64.zip"
          unzip makerom-v0.18-win_x86_64.zip
          move makerom.exe YANBF/generator/makerom.exe
          cd YANBF/generator
          pyinstaller --onefile generator.py
          move dist\generator.exe generator.exe
          rd /s /q dist build __pycache__
          del /q *.py requirements.txt generator.spec
          cd ../..
        shell: cmd
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: YANBF
          name: YANBF-Windows

  macos:
    runs-on: macos-11
    name: Build macOS
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: generator
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: YANBF
          path: YANBF
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install pyinstaller
        run: |
          python3 -m pip install -r YANBF/generator/requirements.txt
      - name: Create package
        run: |
          wget "https://github.com/Epicpkmn11/bannertool/releases/download/1.2.1/bannertool.zip"
          unzip bannertool.zip
          cp mac-x86_64/bannertool YANBF/generator/bannertool
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-macos_x86_64.zip"
          unzip makerom-v0.18-macos_x86_64.zip
          mv -f makerom YANBF/generator/makerom
          cd YANBF/generator
          pyinstaller --onefile generator.py
          mv dist/generator generator
          rm -rf *.py build generator.spec __pycache__ dist requirements.txt
          chmod +x bannertool
          chmod +x makerom
          chmod +x generator
          rm -rf 
          cd ..
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: YANBF
          name: YANBF-macOS

  linux:
    runs-on: ubuntu-latest
    name: Build Linux
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: generator
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: YANBF
          path: YANBF
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pyinstaller
        run: |
          pip3 install -r YANBF/generator/requirements.txt
      - name: Create package
        run: |
          wget "https://github.com/Epicpkmn11/bannertool/releases/download/1.2.1/bannertool.zip"
          unzip bannertool.zip
          cp linux-x86_64/bannertool YANBF/generator/bannertool
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-ubuntu_x86_64.zip"
          unzip makerom-v0.18-ubuntu_x86_64.zip
          mv -f makerom YANBF/generator/makerom
          cd YANBF/generator
          pyinstaller --onefile generator.py
          mv dist/generator generator
          rm -rf *.py build generator.spec __pycache__ dist requirements.txt
          chmod +x makerom
          chmod +x bannertool
          chmod +x generator
          cd ../..
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: YANBF
          name: YANBF-Linux
