name: Build CTR-NDSForwarder Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get tools
        run: |
          sudo cp linux-x86_64/bannertool /usr/local/bin/bannertool && sudo chmod +x /usr/local/bin/bannertool
          wget "https://github.com/ihaveamac/ctr_toolkit/releases/download/make_cia6.4builds/make_cia6.4builds.zip"
          unzip make_cia6.4builds.zip
          sudo cp linux/make_cia /usr/local/bin/make_cia && sudo chmod +x /usr/local/bin/make_cia
      - name: Make CTR-NDSForwarder
        run: |
          make dist
      - name: Prepare for build publishing
        run: |
          mkdir -p ~/artifacts
          cp CTR-NDSForwarder.zip ~/artifacts
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build
      - name: Create zip for Windows
        run: |
          wget "https://github.com/Steveice10/bannertool/releases/download/1.2.0/bannertool.zip"
          unzip bannertool.zip
          mv -f windows-x86_64/bannertool.exe dist/generator/bannertool.exe
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-win_x86_64.zip"
          unzip makerom-v0.18-win_x86_64.zip
          mv -f makerom.exe dist/generator/makerom.exe
          cd dist && zip -r ../CTR-NDSForwarder-Windows.zip *
          rm -rf generator/makerom.exe generator/bannertool.exe
      - name: Create zip for macOS
        run: |
          cp linux-x86_64/bannertool dist/generator/bannertool
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-macos_x86_64.zip"
          unzip makerom-v0.18-macos_x86_64.zip
          mv -f makerom dist/generator/makerom
          cd dist && zip -r ../CTR-NDSForwarder-macOS.zip *
          rm -rf generator/makerom generator/bannertool
      - name: Create zip for Linux
        run: |
          cp linux-x86_64/bannertool dist/generator/bannertool
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-ubuntu_x86_64.zip"
          unzip makerom-v0.18-ubuntu_x86_64.zip
          mv -f makerom dist/generator/makerom
          cd dist && zip -r ../CTR-NDSForwarder-Linux.zip *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CTR-NDSForwarder-Windows.zip
            CTR-NDSForwarder-macOS.zip
            CTR-NDSForwarder-Linux.zip