name: Build YANBF Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get tools
        run: |
          sudo cp linux-x86_64/bannertool /usr/local/bin/bannertool && sudo chmod +x /usr/local/bin/bannertool
          wget "https://github.com/ihaveamac/ctr_toolkit/releases/download/make_cia6.4builds/make_cia6.4builds.zip"
          unzip make_cia6.4builds.zip
          sudo cp linux/make_cia /usr/local/bin/make_cia && sudo chmod +x /usr/local/bin/make_cia
      - name: Make YANBF
        run: |
          make dist
      - name: Prepare for build publishing
        run: |
          mkdir -p ~/artifacts
          cp YANBF.zip ~/artifacts
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build
      - name: Create zip for Windows
        run: |
          wget "https://github.com/Epicpkmn11/bannertool/releases/download/1.2.1/bannertool.zip"
          unzip bannertool.zip
          mv -f windows-x86_64/bannertool.exe dist/generator/bannertool.exe
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-win_x86_64.zip"
          unzip makerom-v0.18-win_x86_64.zip
          mv -f makerom.exe dist/generator/makerom.exe
          wget "https://github.com/Olmectron/Simple-Web-App-GUI-for-YANBF-Generator/releases/download/v1.0.3/yanbf-gui-1.0.3-windows-x64.exe"
          mv -f yanbf-gui-1.0.3-windows-x64.exe dist/generator/yanbf-gui-1.0.3.exe
          cd dist && zip -r ../YANBF-Windows.zip *
          rm -rf generator/makerom.exe generator/bannertool.exe generator/ganbf-gui-1.0.3.exe
      - name: Create zip for macOS
        run: |
          cp mac-x86_64/bannertool dist/generator/bannertool
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-macos_x86_64.zip"
          unzip makerom-v0.18-macos_x86_64.zip
          mv -f makerom dist/generator/makerom
          wget "https://github.com/Olmectron/Simple-Web-App-GUI-for-YANBF-Generator/releases/download/v1.0.3/yanbf-gui-1.0.3-osx.dmg"
          mv -f yanbf-gui-1.0.3-osx.dmg dist/generator/yanbf-gui-1.0.3.dmg
          chmod +x dist/generator/bannertool
          chmod +x dist/generator/makerom
          chmod +x dist/generator/generator.py
          cd dist && zip -r ../YANBF-macOS.zip *
          rm -rf generator/makerom generator/bannertool generator/yanbf-gui-1.0.3.dmg
      - name: Create zip for Linux
        run: |
          cp linux-x86_64/bannertool dist/generator/bannertool
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-ubuntu_x86_64.zip"
          unzip makerom-v0.18-ubuntu_x86_64.zip
          mv -f makerom dist/generator/makerom
          wget "https://github.com/Olmectron/Simple-Web-App-GUI-for-YANBF-Generator/releases/download/v1.0.3/yanbf-gui-1.0.3-linux.AppImage"
          mv -f yanbf-gui-1.0.3-linux.AppImage dist/generator/yanbf-gui-1.0.3.AppImage
          chmod +x dist/generator/makerom
          chmod +x dist/generator/bannertool
          chmod +x dist/generator/generator.py
          cd dist && zip -r ../YANBF-Linux.zip *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            YANBF-Windows.zip
            YANBF-macOS.zip
            YANBF-Linux.zip